# Generated by Django 3.1.14 on 2022-12-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pokemonentity_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='appeard_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Appeard at'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='disappeard_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Disappeard at'),
        ),
    ]
