# Generated by Django 3.1.14 on 2023-01-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_auto_20230106_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='appeard_at',
            new_name='appeared_at',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='disappeard_at',
            new_name='disappeared_at',
        ),
    ]
