# Generated by Django 3.1.14 on 2023-01-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0016_auto_20230106_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='kind',
            new_name='pokemon',
        ),
    ]
